# This is an example workflow that scans a Python open-source pacakge via a git URL
# You can use this as an example for your own remote scans
name: Scan Example Test
on:
  workflow_dispatch:

jobs:
  endor-scan:
    uses: arsalanendor/paolo_poc/.github/workflows/scan-with-endorlabs.yml@main
    permissions:
      id-token: write      # allows authentication to Endor Labs using Actions OIDC JWT Token
      contents: read       # allows this job to clone org repos
    with:
      git-url: "https://github.com/arsalan-learn/defaults_txt.git" 
      namespace: arsalan-learn
      upload-json: true
      is-pr: true
    secrets:
      #endorlabs-api-auth: ${{ secrets.ENDORLABS_API_AUTH }}
      # to operate on a private repo, generate a github access token with `repo` rights
      # and create an orgization or repository secret named `GITHUB_ACCESS_TOKEN`, then
      # uncomment the line below
      github-access-token: ${{ secrets.SIDECAR_ACCESS_TOKEN }}
